### ISSUE TITLE
New git/composer release?

### ISSUE THREAD

**Issue by Hikariii** [slimphp/PHP-View#111]
Hello,
I have a blocking dependency on a package requiring `"psr/http-message": "^2.0"`.
This commit solves that issue.
https://github.com/slimphp/PHP-View/commit/ef1821663a6a028b9e446e8c6818fd257bf70313

Can you release the current master as a new version?

**Comment by odan** [comment]
This will be released today.

**Comment by odan** [comment]
Done. See here: https://github.com/slimphp/PHP-View/releases/tag/3.4.0
