### ISSUE TITLE
Need consistent naming to fix autoloading

### ISSUE THREAD

**Issue by josephscott** [slimphp/PHP-View#12]
As it stands right now PHP-View doesn't work because the Composer autoloader doesn't match a `PhpRenderer` class name against a `PHPRenderer.php` file name.

One of two things needs to happen:
- Change the filename from `PHPRenderer.php` to `PhpRenderer.php`
- Change the class name from `PhpRenderer` to `PHPRenderer`

Both of these approaches fixed autoloading for me.  I suspect the first option would be preferred, but I'd be fine with either one since I'm more concerned about it working than the naming style.

**Comment by akrabat** [comment]
I'd prefer the first one too.

**Comment by geggleto** [comment]
interesting that it works fine for me when I run the tests locally ...

**Comment by akrabat** [comment]
Fixed with PR #13. 

@josephscott I'd appreciate it if you could test and confirm.

**Comment by geggleto** [comment]
At least in my case I didn't have the issue to begin with.
Thanks @josephscott

**Comment by josephscott** [comment]
@akrabat confirmed, 2.0.5 works fine.

@geggleto any chance you are using a filesystem that is not case sensitive?

**Comment by geggleto** [comment]
@josephscott  Yeah I am on windows ;)
