### ISSUE TITLE
Rendering templates from a sub-directory

### ISSUE THREAD

**Issue by cleartext** [slimphp/PHP-View#18]
Is this possible?

I have a template in a sub directory (within the template directory) but ?php include('header.phtml'); is not working, neither does it if I put slash / (root?) in front.

With Twig I could do;

{% include('header.php') %}

And that 'just worked' wherever the files was from the root of the template dir down.

thanks,

David,

**Comment by geggleto** [comment]
you can use directory traversal... in your include statements. ` include "../_parent_dir/templates2/template.php"

?

**Comment by cleartext** [comment]
Well, I had tried that, a few times but obviously had the end of day heebeegeebies... it works now.

Thanks for pushing me back that way. I didn't try going back to the templates directory....

**Comment by geggleto** [comment]
Np :)
