### ISSUE TITLE
can we do something to avoid XSS Attack?

### ISSUE THREAD

**Issue by wyixin** [slimphp/PHP-View#26]
just coding as following:
```
    $name = '<script>alert("1");</script>';
    $renderer->render($response, "home.phtml", ['name'] => $name);
```

**Comment by akrabat** [comment]
If you're using PHP-View rather than Twig-View, then it is the developer's responsibility to use `htmlspecialchars()` or [`zend-escaper`](https://github.com/zendframework/zend-escaper).

We should probably note this in the README.

**Comment by akrabat** [comment]
README updated.
