### ISSUE TITLE
PhpRenderer::render() manipulates input response

### ISSUE THREAD

**Issue by futape** [slimphp/PHP-View#46]
Haven't tested it, but to me it seems as if the `render` method work *on* the input response itself instead of cloning it (as described [here](http://www.slimframework.com/docs/v3/tutorial/first-app.html#views-and-templates)).

> Response objects are immutable which means that the call to render() won’t update the response object; instead it will return us a new object which is why it needs to be captured like this. This is always true when you operate on the response object.

**Comment by l0gicgate** [comment]
It's manipulating the body of the response, which is just an underlying stream that isn't immutable.

`$response->getBody()->write($output);`
