### ISSUE TITLE
Return Json

### ISSUE THREAD

**Issue by nicolahsss** [slimphp/PHP-View#47]
Como retornar o header application/json.

Tentei 
header('Content-Type: application/json');
$response->withHeader('Content-Type', 'application/json');

Porem sem sucesso

**Comment by l0gicgate** [comment]
I'm not sure I understand the question but to return JSON:
```php
$payload = json_encode(['your' => 'payload']);
$response->getBody()->write($payload);
return $response->withHeader('Content-Type', 'application/json');
```
