### ISSUE TITLE
Sub-templates and layouts

### ISSUE THREAD

**Issue by gdsmith** [slimphp/PHP-View#49]
From the documentation:

> Inside your templates you may use $this to refer to the PhpRenderer object to render sub-templates.

Including sub-templates (with `fetch`) when you are using layouts is problematic as sub-template content also includes the surrounding layout. Using a straight php `include(template.file)` is an effective workaround.

**Comment by vasiliytkachenko** [comment]
slim/php-view/src/PhpRenderer.php

method fetch 

if ($this->layout !== null) {
                ob_start();
                $data['content'] = $output;
                $this->protectedIncludeScope($this->layout, $data);
                $output = ob_get_clean(); 
            }

maybe the problem is here      $this->layout == null

**Comment by kAlvaro** [comment]
README explains you can render sub-templates but doesn't say *how*:
- If you are meant to use `\Slim\Views\PhpRenderer::fetch()`, as in `<footer><?php echo $this->fetch('footer.phtml'); ?></footer>`, then you get *Maximum function nesting level of '256' reached, aborting!* breaking an infinite loop.
- If that isn't the way, I guess docs need a tweak.

**Comment by jaywilliams** [comment]
Here's a potential patch I created which gives a workaround for template-less partials:

```patch
--- PhpRenderer.php.orig        Mon Aug 19 15:37:38 2019
+++ PhpRenderer.php     Mon Aug 19 15:39:37 2019
@@ -204,7 +204,7 @@
             $this->protectedIncludeScope($this->templatePath . $template, $data);
             $output = ob_get_clean();

-            if ($this->layout !== null) {
+            if ($data['layout'] !== false && $data['layout'] !== '' && $this->layout !== null) {
                 ob_start();
                 $data['content'] = $output;
                 $this->protectedIncludeScope($this->layout, $data);
```

Usage:
```php
    echo $this->fetch('partials/test.phtml', [
        'layout'  => false,
    ]);
```

Another possibility would be to create a separate method which wouldn't include the layout, regardless (e.g.`$this->fetchPartial('partials/test.phtml')`).

**Comment by piotr-cz** [comment]
@jaywilliams 
Thanks, I just suggest changing the flag to `skipLayout`, so evaluation becomes easier:

```diff
- if ($this->layout !== null) {
+ if ($this->layout !== null && empty($data['skipLayout'])) {
```

**Comment by piotr-cz** [comment]
If anyone is wondering about the status,
bugfix #53 was implied to be a B/C feature and merged into 3.x branch.
