### ISSUE TITLE
response leaking into view

### ISSUE THREAD

**Issue by piotr-cz** [slimphp/PHP-View#5]
When directly including a file, all scope variables are leaking so in effect it's possible to modify the `$response` and `$this` variables from within the template.

I think there could be an anonymous function inside the render method with own scope:

```php
$render = function() {
    extract(func_get_arg(1));
    return include func_get_arg(0);
};

ob_start();
$render($this->templatePath . $template, $data);
$output = ob_get_clean();
```

[source](http://stackoverflow.com/a/8516455/1012616)

**Comment by geggleto** [comment]
I am okay with leaking $this ,since I will be adding additional methods to the class.
I can see leaking $response as possibly being a problem... 

No need for func magic
```
$render = function($template, $data) {
    extract($data);
    return include $template;
};

ob_start();
$render($this->templatePath . $template, $data);
$output = ob_get_clean();
```

Will PR later today

**Comment by geggleto** [comment]
See #6

**Comment by piotr-cz** [comment]
As you mention, leaking `$this` has some advantages, however I'd prefer having separate API as for example it could be possible to change the template path (`$this->template`). 

Thanks!
